theme: "jekyll-theme-cayman"
title: "Workshop Ciência de Dados"
subtitle: "<img src=img/logo.png width = '30%'>"
description: Materiais apresentados no Workshop Ciência de Dados.
github:
  is_project_page: false
